"""4 Added bettable and bets, renamed event to matches

Revision ID: 6eb849c40c61
Revises: 92a4cfcea209
Create Date: 2018-06-24 11:57:24.441764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6eb849c40c61'
down_revision = '92a4cfcea209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('team1_id', sa.Integer(), nullable=True),
    sa.Column('team2_id', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bettable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opened_since', sa.DateTime(), nullable=True),
    sa.Column('closed_from', sa.DateTime(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bettable_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('submitted_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bettable_id'], ['bettable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    op.add_column('team', sa.Column('flag_picture', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'user', 'identity', ['identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('team', 'flag_picture')
    op.create_table('event',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('picture', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('open_since', mysql.DATETIME(), nullable=True),
    sa.Column('closes_from', mysql.DATETIME(), nullable=True),
    sa.Column('team1_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('team2_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('finished', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('score1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('score2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.drop_table('bet')
    op.drop_table('bettable')
    op.drop_table('match')
    # ### end Alembic commands ###
