"""rename is_admin to can_be_admin

Revision ID: 9a6bae6e1e66
Revises: f814138f7d72
Create Date: 2018-06-25 20:49:43.919461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a6bae6e1e66'
down_revision = 'f814138f7d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bet', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bet', 'bettable', ['bettable_id'], ['id'])
    op.create_foreign_key(None, 'bettable', 'match', ['match_id'], ['id'])
    op.create_foreign_key(None, 'match', 'team', ['team2_id'], ['id'])
    op.create_foreign_key(None, 'match', 'team', ['team1_id'], ['id'])
    op.add_column('user', sa.Column('can_be_admin', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user', 'identity', ['identity_id'], ['id'])
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'can_be_admin')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'bettable', type_='foreignkey')
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.drop_constraint(None, 'bet', type_='foreignkey')
    # ### end Alembic commands ###
