"""6 Add fifa code to team model

Revision ID: a04b18b2b725
Revises: f0712a51a3a9
Create Date: 2018-06-24 17:29:02.654245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04b18b2b725'
down_revision = 'f0712a51a3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bet', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bet', 'bettable', ['bettable_id'], ['id'])
    op.create_foreign_key(None, 'bettable', 'match', ['match_id'], ['id'])
    op.create_foreign_key(None, 'match', 'team', ['team1_id'], ['id'])
    op.create_foreign_key(None, 'match', 'team', ['team2_id'], ['id'])
    op.add_column('team', sa.Column('code_fifa', sa.String(length=3), nullable=False))
    op.create_unique_constraint(None, 'team', ['code_fifa'])
    op.create_foreign_key(None, 'user', 'identity', ['identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_column('team', 'code_fifa')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'bettable', type_='foreignkey')
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.drop_constraint(None, 'bet', type_='foreignkey')
    # ### end Alembic commands ###
