"""empty message

Revision ID: e56dd1052145
Revises: 3ffd1976ed01
Create Date: 2018-06-23 12:02:50.088692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e56dd1052145'
down_revision = '3ffd1976ed01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity', sa.Column('first_name', sa.String(length=200), nullable=True))
    op.add_column('identity', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('identity', sa.Column('last_name', sa.String(length=200), nullable=True))
    op.drop_column('identity', 'name')
    op.create_foreign_key(None, 'user', 'identity', ['identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('identity', sa.Column('name', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('identity', 'last_name')
    op.drop_column('identity', 'full_name')
    op.drop_column('identity', 'first_name')
    # ### end Alembic commands ###
