"""5 Updated team model

Revision ID: f0712a51a3a9
Revises: 6eb849c40c61
Create Date: 2018-06-24 16:49:49.886578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0712a51a3a9'
down_revision = '6eb849c40c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bet', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bet', 'bettable', ['bettable_id'], ['id'])
    op.create_foreign_key(None, 'bettable', 'match', ['match_id'], ['id'])
    op.create_foreign_key(None, 'match', 'team', ['team2_id'], ['id'])
    op.create_foreign_key(None, 'match', 'team', ['team1_id'], ['id'])
    op.add_column('team', sa.Column('population', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'identity', ['identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('team', 'population')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'bettable', type_='foreignkey')
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.drop_constraint(None, 'bet', type_='foreignkey')
    # ### end Alembic commands ###
